name: Build

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-12, windows-2022]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: 1.5.1
    - name: Create build
      shell: bash
      run: make
    - name: Run Tests
      run: poetry run pytest
